# Generated by Django 2.1.4 on 2018-12-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181214_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='choice_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.ChoiceIndex'),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='choice_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.ChoiceType'),
        ),
    ]
