# Generated by Django 2.1.4 on 2018-12-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181216_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
