# Generated by Django 2.1.4 on 2018-12-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181216_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
